spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/community
    username: postgres
    password: neyzen1997
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root=INFO:


